"""small changes in making: username replaces phone as unique login identifier

Revision ID: 7a30a692ec87
Revises: 182f276a6fc0
Create Date: 2026-09-23 16:45:14.046556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a30a692ec87'
down_revision: Union[str, Sequence[str], None] = '182f276a6fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
