"""add subjects chapters room_subjects

Revision ID: fc42ab2fc59f
Revises: 7a30a692ec87
Create Date: 2026-09-28 18:09:12.880798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc42ab2fc59f'
down_revision: Union[str, Sequence[str], None] = '7a30a692ec87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_subject_teacher_name')
    )
    op.create_index(op.f('ix_subjects_teacher_id'), 'subjects', ['teacher_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'failed', name='chapter_status'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_file_hash'), 'chapters', ['file_hash'], unique=False)
    op.create_index(op.f('ix_chapters_subject_id'), 'chapters', ['subject_id'], unique=False)
    op.create_table('room_subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'subject_id', name='uq_room_subject')
    )
    op.create_index(op.f('ix_room_subjects_room_id'), 'room_subjects', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_subjects_subject_id'), 'room_subjects', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_subjects_subject_id'), table_name='room_subjects')
    op.drop_index(op.f('ix_room_subjects_room_id'), table_name='room_subjects')
    op.drop_table('room_subjects')
    op.drop_index(op.f('ix_chapters_subject_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_file_hash'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_subjects_teacher_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
